[package]
name = "day10"
version = "0.1.0"
authors = ["Julien Gaston <gaston@codelutin.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.5.1"
ndarray = "0.14.0"
