[package]
name = "day4"
version = "0.1.0"
authors = ["Julien Gaston <gaston@codelutin.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
lazy_static = "0.1.*"